language: ruby
rvm:
  - 2.5.3
before_install:
  - gem install bundler
script:
  - ruby -Ilib -e 'ARGV.each { |f| require f }' ./_tests/*.rb
  - bundle exec jekyll build --future --drafts
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --url-ignore /www.worthwelle.com/
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer